version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: ~/myself
    branches:
      only:
        - master
    steps:
      - checkout
      - run: apt-get install docker-ce docker-ce-cli containerd.io
      - run: npm install
      - run: npm run build
      - run: docker build -t ${CIRCLE-SHA1}
      - run: docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
      - run: docker push ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_APP}:${CIRCLE-SHA1}
