version: 2
jobs:
  build:
    docker:
      - image: node:latest
    branches:
      only:
        - master
    working_directory: ~/myself
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="latest"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run build
      - run: docker build -t $DOCKER_HUB_USERNAME/$DOCKER_HUB_APP:$CIRCLE_SHA1 .
      - run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - run: docker push $DOCKER_HUB_USERNAME/$DOCKER_HUB_APP:$CIRCLE_SHA1
